// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import './axiosConfig.js'; 
import { AuthProvider } from './login/auth';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "LABORATORY ERP",
//   description: "Generated by ASKSYSTEMS",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        <AuthProvider>
          {children}{/* Render the client-side auth logic in children */}
        </AuthProvider>
      </body>
    </html>
  );
}
