// src/models/exame.ts
export interface Exame {
    cod?: number;  // Equivalente ao campo "ID" no C#
    codigo_exame?: string;  // Corresponde a "CODIGO_EXAME"
    exame: string;  // Mapeia o campo "EXAME"
    prazo: number;  // Mapeia o campo "PRAZO"
    metodo?: string;  // Corresponde a "METODO"
    preparo?: string;  // Corresponde a "PREPARO"
    preparof?: string;  // Corresponde a "PREPAROF"
    preparoc?: string;  // Corresponde a "PREPAROC"
    agenda?: boolean;  // Corresponde a "AGENDA"
    agendasrelacionadas?: string;  // Corresponde a "AGENDASRELACIONADAS"
    destino?: string;  // Corresponde a "DESTINO"
    sinonimos?: string;  // Corresponde a "SINONIMOS"
    dissociar?: boolean;  // Corresponde a "DISSOCIAR"
    formulario?: string;  // Corresponde a "FORMULARIO"
    instrucoesdepreparo?: string;  // Corresponde a "INSTRUCOESDEPREPARO"
    coleta?: string;  // Corresponde a "COLETA"
    distribuicao?: string;  // Corresponde a "DISTRIBUICAO"
    lembretes?: string;  // Corresponde a "LEMBRETES"
    tecnicadecoleta?: string;  // Corresponde a "TECNICADECOLETA"
    alertasrecep?: string;  // Corresponde a "ALERTASRECEP"
    alertasrecepos?: string;  // Corresponde a "ALERTASRECEPOS"
    alertas?: string;  // Corresponde a "ALERTAS"
    alertaspos?: string;  // Corresponde a "ALERTASPOS"
    slexamesref_tabela_cod?: string;  // Corresponde a "SLEXAMESREF_TABELA_COD"
    slexamesref_tabela_exame?: string;  // Corresponde a "SLEXAMESREF_TABELA_EXAME"
    slexamesref_tabela_conv?: string;  // Corresponde a "SLEXAMESREF_TABELA_CONV"
    slexamesref_tabela_plano?: string;  // Corresponde a "SLEXAMESREF_TABELA_PLANO"
    slexamesref_tabela_aut?: string;  // Corresponde a "SLEXAMESREF_TABELA_AUT"
    slexamesref_tabela_valor: number;  // Mapeia o campo "SLEXAMESREF_TABELA_VALOR"
    estabilidade?: string;  // Corresponde a "ESTABILIDADE"
    material_apoio_id: number;  // Corresponde a "MATERIAL_APOIO_ID"
    epecialidade_id: number;  // Corresponde a "EPECIALIDADE_ID"
    setor_id: number;  // Corresponde a "SETOR_ID"
  }  